# Generated by Django 5.1.1 on 2025-02-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontendUser",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女"), ("O", "其他")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[("G1", "高一"), ("G2", "高二"), ("G3", "高三")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "类别", "verbose_name_plural": "类别"},
        ),
        migrations.RemoveField(
            model_name="problem",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="image",
        ),
        migrations.RemoveField(
            model_name="userconversation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="problem",
            name="question_number",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ExamSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="examsets/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="users.category")),
            ],
        ),
        migrations.AddField(
            model_name="problem",
            name="exam_set",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problems",
                to="users.examset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userconversation",
            name="frontend_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.frontenduser",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userhistory",
            name="frontend_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.frontenduser",
            ),
            preserve_default=False,
        ),
    ]
