# Generated by Django 5.1.1 on 2025-02-17 10:08

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_apiconfig_alter_frontenduser_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconfig",
            name="api_secret",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="app_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="extra_params",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="host",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="frontenduser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.user_avatar_path
            ),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI API"),
                    ("google", "Google API"),
                    ("baidu", "Baidu API"),
                    ("deepseek", "DeepSeek API"),
                    ("xfyun", "讯飞星火 API"),
                    ("custom", "自定义 API"),
                ],
                max_length=50,
            ),
        ),
    ]
