# Generated by Django 5.1.1 on 2025-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_apiconfig_api_secret_apiconfig_app_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontenduser",
            name="correct_problems",
            field=models.IntegerField(default=0),
        ),
    ]
